/**
 * S79c (F24) — AI Conversation export to markdown smoke.
 *
 * Verifies the buildConversationMarkdown contract — the function lives as
 * 3 sibling copies (portal/admin/cashier) but they MUST stay in sync. This
 * smoke runs a single mirror of the function against a battery of inputs
 * and asserts on the output string. If the 3 copies drift apart, this test
 * doesn't catch it directly — but the contract is small enough that any
 * drift would be obvious in code review.
 *
 * Tests:
 *   1. Empty messages array → "(empty conversation)" placeholder
 *   2. Single user message → header + content + footer
 *   3. User → assistant exchange → both headings rendered
 *   4. Tool calls render as "_Tools used: ..._" line
 *   5. Ticket reference renders as "_Filed support ticket: ..._" line
 *   6. Feedback renders 👍/👎 with optional note
 *   7. Empty content → "(empty message)" placeholder
 *   8. Tool labels mapped from TOOL_LABELS dict, fallback to raw name
 *   9. createdAt parses to locale string
 *  10. Title comes from conversation.title (or default)
 *  11. Filename builder: convId suffix + ISO date
 *  12. Markdown structure: --- separators between messages
 *  13. Multi-tool calls labeled in order
 *  14. Special chars in content: NOT html-escaped (markdown is plain text)
 *  15. Long content preserved verbatim (no truncation)
 */

let pass = 0, fail = 0;
const log = (label, ok, detail = '') => {
  const sym = ok ? '✓' : '✗';
  console.log(`  ${sym} ${label}${detail ? '  — ' + detail : ''}`);
  if (ok) pass++; else fail++;
};

console.log('=== S79c (F24) AI CONVERSATION EXPORT — PURE-FUNCTION SMOKE ===\n');

// ── Mirror of buildConversationMarkdown (all 3 widgets) ──────────────
function buildConversationMarkdown(conversation, messages, opts = {}) {
  const toolLabels = opts.toolLabels || {};
  const lines = [];
  const title = conversation?.title || 'AI Assistant Conversation';
  const exportDate = new Date().toLocaleString();
  const count = Array.isArray(messages) ? messages.length : 0;

  lines.push(`# ${title}`);
  lines.push('');
  lines.push(`_Exported ${exportDate} · ${count} message${count === 1 ? '' : 's'}_`);
  lines.push('');
  lines.push('---');
  lines.push('');

  if (count === 0) {
    lines.push('_(empty conversation)_');
  } else {
    for (const m of messages) {
      const ts = m.createdAt ? new Date(m.createdAt).toLocaleString() : '';
      const heading = m.role === 'user'
        ? `## 👤 You${ts ? ' · ' + ts : ''}`
        : `## 🤖 Assistant${ts ? ' · ' + ts : ''}`;
      lines.push(heading);
      lines.push('');
      lines.push((m.content || '').trim() || '_(empty message)_');

      if (Array.isArray(m.toolCalls) && m.toolCalls.length > 0) {
        const labels = m.toolCalls
          .map(t => toolLabels[t.name] || t.name)
          .filter(Boolean);
        if (labels.length > 0) {
          lines.push('');
          lines.push(`_Tools used: ${labels.join(', ')}_`);
        }
      }

      if (m.ticketId) {
        lines.push('');
        lines.push(`_Filed support ticket: ${m.ticketId}_`);
      }

      if (m.feedback === 'helpful' || m.feedback === 'unhelpful') {
        lines.push('');
        lines.push(`_Feedback: ${m.feedback === 'helpful' ? '👍' : '👎'}${m.feedbackNote ? ' — ' + m.feedbackNote : ''}_`);
      }

      lines.push('');
      lines.push('---');
      lines.push('');
    }
  }

  lines.push('');
  lines.push('_Generated by StoreVeu AI Assistant_');
  return lines.join('\n');
}

function buildExportFilename(conversationId) {
  const idSuffix = (conversationId || '').slice(-6) || 'session';
  const date = new Date().toISOString().slice(0, 10);
  return `ai-conversation-${idSuffix}-${date}.md`;
}

// ── 1. Empty messages ────────────────────────────────────────────────
console.log('[1] Empty messages → placeholder');
{
  const md = buildConversationMarkdown(null, [], {});
  log('starts with default title', md.startsWith('# AI Assistant Conversation'));
  log('shows "0 messages"', /0 messages/.test(md));
  log('contains empty placeholder', /_\(empty conversation\)_/.test(md));
  log('ends with generated footer', /Generated by StoreVeu AI Assistant_$/.test(md));
}

// ── 2. Single user message ───────────────────────────────────────────
console.log('\n[2] Single user message');
{
  const md = buildConversationMarkdown(null, [
    { role: 'user', content: 'How are sales today?', createdAt: '2026-05-04T14:00:00Z' },
  ], {});
  log('renders user heading',     /## 👤 You/.test(md));
  log('does NOT render assistant heading', !/## 🤖 Assistant/.test(md));
  log('contains user content',    md.includes('How are sales today?'));
  log('shows "1 message" (singular)', /1 message[^s]/.test(md));
  log('has trailing separator',   md.includes('---'));
}

// ── 3. User → Assistant exchange ─────────────────────────────────────
console.log('\n[3] User → Assistant exchange');
{
  const md = buildConversationMarkdown(null, [
    { role: 'user',      content: 'How are sales today?', createdAt: '2026-05-04T14:00:00Z' },
    { role: 'assistant', content: 'Today\'s sales: $542.50 across 12 transactions.', createdAt: '2026-05-04T14:00:05Z' },
  ], {});
  log('shows "2 messages" (plural)', /2 messages/.test(md));
  log('user heading present',        /## 👤 You/.test(md));
  log('assistant heading present',   /## 🤖 Assistant/.test(md));
  log('user content present',        md.includes('How are sales today?'));
  log('assistant content present',   md.includes('$542.50'));
  // User comes BEFORE assistant
  const userIdx = md.indexOf('## 👤 You');
  const asstIdx = md.indexOf('## 🤖 Assistant');
  log('order preserved (user before assistant)', userIdx < asstIdx);
}

// ── 4. Tool calls ────────────────────────────────────────────────────
console.log('\n[4] Tool calls');
{
  const TOOL_LABELS = {
    get_store_summary:    'Sales summary',
    get_inventory_status: 'Inventory check',
  };
  const md = buildConversationMarkdown(null, [
    {
      role: 'assistant',
      content: 'Sales today: $500.',
      toolCalls: [
        { name: 'get_store_summary', input: {} },
        { name: 'get_inventory_status', input: {} },
      ],
    },
  ], { toolLabels: TOOL_LABELS });

  log('renders "Tools used" line', md.includes('_Tools used:'));
  log('first tool labeled',         md.includes('Sales summary'));
  log('second tool labeled',        md.includes('Inventory check'));
  log('tool labels in order',       md.indexOf('Sales summary') < md.indexOf('Inventory check'));
  log('comma-separated',            md.includes('Sales summary, Inventory check'));
}

console.log('\n[4b] Tool calls — fallback to raw name when not in dict');
{
  const md = buildConversationMarkdown(null, [
    {
      role: 'assistant',
      content: 'Done.',
      toolCalls: [{ name: 'unknown_tool', input: {} }],
    },
  ], { toolLabels: { get_store_summary: 'Sales summary' } });

  log('falls back to raw tool name', md.includes('unknown_tool'));
}

console.log('\n[4c] Tool calls — null/empty/missing array');
{
  const a = buildConversationMarkdown(null, [{ role: 'assistant', content: 'X' }], {});
  log('no toolCalls field → no Tools line',     !a.includes('_Tools used'));
  const b = buildConversationMarkdown(null, [{ role: 'assistant', content: 'X', toolCalls: [] }], {});
  log('empty toolCalls array → no Tools line',  !b.includes('_Tools used'));
  const c = buildConversationMarkdown(null, [{ role: 'assistant', content: 'X', toolCalls: null }], {});
  log('null toolCalls → no Tools line',         !c.includes('_Tools used'));
}

// ── 5. Ticket reference ──────────────────────────────────────────────
console.log('\n[5] Ticket reference');
{
  const md = buildConversationMarkdown(null, [
    { role: 'assistant', content: 'I\'ll file a ticket.', ticketId: 'TICKET-12345' },
  ], {});
  log('contains ticket line', /_Filed support ticket: TICKET-12345_/.test(md));

  const noTicket = buildConversationMarkdown(null, [
    { role: 'assistant', content: 'Resolved.' },
  ], {});
  log('no ticket → no ticket line', !noTicket.includes('Filed support ticket'));
}

// ── 6. Feedback rendering ────────────────────────────────────────────
console.log('\n[6] Feedback rendering');
{
  const helpful = buildConversationMarkdown(null, [
    { role: 'assistant', content: 'Hi.', feedback: 'helpful' },
  ], {});
  log('helpful feedback → 👍',  /_Feedback: 👍_/.test(helpful));

  const unhelpful = buildConversationMarkdown(null, [
    { role: 'assistant', content: 'Hi.', feedback: 'unhelpful' },
  ], {});
  log('unhelpful feedback → 👎', /_Feedback: 👎_/.test(unhelpful));

  const withNote = buildConversationMarkdown(null, [
    { role: 'assistant', content: 'Hi.', feedback: 'unhelpful', feedbackNote: 'Wrong info' },
  ], {});
  log('feedback with note',     /_Feedback: 👎 — Wrong info_/.test(withNote));

  const noFeedback = buildConversationMarkdown(null, [
    { role: 'assistant', content: 'Hi.' },
  ], {});
  log('no feedback → no feedback line', !noFeedback.includes('Feedback'));

  const bogusFeedback = buildConversationMarkdown(null, [
    { role: 'assistant', content: 'Hi.', feedback: 'unrecognized' },
  ], {});
  log('bogus feedback value → no feedback line', !bogusFeedback.includes('_Feedback'));
}

// ── 7. Empty content → placeholder ───────────────────────────────────
console.log('\n[7] Empty content → placeholder');
{
  const empty = buildConversationMarkdown(null, [
    { role: 'user', content: '' },
  ], {});
  log('empty string → placeholder',    empty.includes('_(empty message)_'));

  const whitespace = buildConversationMarkdown(null, [
    { role: 'user', content: '   \n\t  ' },
  ], {});
  log('whitespace-only → placeholder', whitespace.includes('_(empty message)_'));

  const undef = buildConversationMarkdown(null, [
    { role: 'user' /* content omitted */ },
  ], {});
  log('missing content → placeholder', undef.includes('_(empty message)_'));
}

// ── 8. Conversation title ────────────────────────────────────────────
console.log('\n[8] Conversation title fallback');
{
  const withTitle = buildConversationMarkdown({ title: 'My Custom Title' }, [], {});
  log('uses custom title',  withTitle.startsWith('# My Custom Title'));

  const noTitle = buildConversationMarkdown({ title: null }, [], {});
  log('null title → default', noTitle.startsWith('# AI Assistant Conversation'));

  const noConv = buildConversationMarkdown(null, [], {});
  log('null conversation → default', noConv.startsWith('# AI Assistant Conversation'));

  const emptyConv = buildConversationMarkdown({}, [], {});
  log('empty conversation → default', emptyConv.startsWith('# AI Assistant Conversation'));
}

// ── 9. createdAt parsing ─────────────────────────────────────────────
console.log('\n[9] createdAt parsing');
{
  const withDate = buildConversationMarkdown(null, [
    { role: 'user', content: 'Hi', createdAt: '2026-05-04T14:00:00Z' },
  ], {});
  log('createdAt rendered',    /## 👤 You · /.test(withDate));

  const noDate = buildConversationMarkdown(null, [
    { role: 'user', content: 'Hi' },
  ], {});
  log('missing createdAt → no separator dot', !/## 👤 You · /.test(noDate));

  // Also accepts Date object
  const dateObj = buildConversationMarkdown(null, [
    { role: 'user', content: 'Hi', createdAt: new Date('2026-05-04T14:00:00Z') },
  ], {});
  log('Date object accepted', /## 👤 You · /.test(dateObj));
}

// ── 10. Filename builder ─────────────────────────────────────────────
console.log('\n[10] Filename builder');
{
  const today = new Date().toISOString().slice(0, 10);

  // Long cuid: last 6 chars of 'cmo8uufzq0000h5k3psylas8r' = 'ylas8r'
  const longId = 'cmo8uufzq0000h5k3psylas8r';
  const expectedSuffix = longId.slice(-6); // 'ylas8r'
  log(`long convId → last 6 chars (${expectedSuffix})`,
    buildExportFilename(longId) === `ai-conversation-${expectedSuffix}-${today}.md`);

  log('null id → "session" placeholder',
    buildExportFilename(null) === `ai-conversation-session-${today}.md`);
  log('empty id → "session"',
    buildExportFilename('') === `ai-conversation-session-${today}.md`);

  log('always ends with .md', buildExportFilename('xyz').endsWith('.md'));

  // Short id (< 6 chars) — slice(-6) returns the whole string, fine
  log('short id passes through',
    buildExportFilename('abc') === `ai-conversation-abc-${today}.md`);

  // Date format: ISO date (YYYY-MM-DD)
  log('filename includes ISO date', buildExportFilename('xyz').includes(today));
}

// ── 11. Markdown structure: separators ──────────────────────────────
console.log('\n[11] Markdown structure');
{
  const md = buildConversationMarkdown(null, [
    { role: 'user', content: 'A' },
    { role: 'assistant', content: 'B' },
    { role: 'user', content: 'C' },
  ], {});

  // 3 messages should produce 3 inter-message separators + 1 top separator = 4 total
  const sepCount = (md.match(/^---$/gm) || []).length;
  log('3 messages → 4 separators (1 top + 3 between)', sepCount === 4);

  log('h1 title', /^# AI Assistant Conversation$/m.test(md));
  log('h2 user heading', /^## 👤 You$/m.test(md));
  log('h2 assistant heading', /^## 🤖 Assistant$/m.test(md));
}

// ── 12. Special chars NOT escaped (markdown is plain text) ──────────
console.log('\n[12] Special chars preserved (NOT HTML-escaped)');
{
  const md = buildConversationMarkdown(null, [
    { role: 'user', content: '<div>Hello & "world" <script>' },
  ], {});
  // We're producing markdown for download, NOT rendering HTML.
  // Special chars should pass through verbatim — markdown is plain text.
  log('< not escaped',  md.includes('<div>'));
  log('& not escaped',  md.includes(' & '));
  log('" not escaped',  md.includes('"world"'));
  log('<script> preserved (it\'s a download, not rendered)', md.includes('<script>'));
}

// ── 13. Long content preserved verbatim ──────────────────────────────
console.log('\n[13] Long content preserved');
{
  const longContent = 'A'.repeat(5000) + '\n\nMiddle paragraph\n\n' + 'B'.repeat(5000);
  const md = buildConversationMarkdown(null, [
    { role: 'assistant', content: longContent },
  ], {});
  log('long content fully present', md.includes(longContent));
  log('newlines preserved', md.includes('\n\nMiddle paragraph\n\n'));
}

// ── 14. Markdown formatting passes through ──────────────────────────
console.log('\n[14] Claude markdown formatting passes through unchanged');
{
  const claudeOutput = `Here's a list:

1. **Bold item**
2. *Italic item*
3. \`code item\`

| Header | Value |
|--------|-------|
| A | 1 |

\`\`\`js
console.log('hello');
\`\`\``;
  const md = buildConversationMarkdown(null, [
    { role: 'assistant', content: claudeOutput },
  ], {});
  log('bold passes through',     md.includes('**Bold item**'));
  log('italic passes through',   md.includes('*Italic item*'));
  log('inline code passes',      md.includes('`code item`'));
  log('table passes through',    md.includes('| Header | Value |'));
  log('code block passes',       md.includes('```js'));
  log('code block content',      md.includes("console.log('hello');"));
}

// ── 15. All assistant features in one message ───────────────────────
console.log('\n[15] All assistant features stacked');
{
  const md = buildConversationMarkdown(null, [
    {
      role: 'assistant',
      content: 'Result.',
      toolCalls: [{ name: 'get_store_summary' }],
      ticketId: 'T-99',
      feedback: 'helpful',
      feedbackNote: 'Great',
    },
  ], { toolLabels: { get_store_summary: 'Sales summary' } });

  log('content rendered',   md.includes('Result.'));
  log('tools rendered',     md.includes('_Tools used: Sales summary_'));
  log('ticket rendered',    md.includes('_Filed support ticket: T-99_'));
  log('feedback rendered',  md.includes('_Feedback: 👍 — Great_'));

  // Order: content → tools → ticket → feedback
  const contentIdx  = md.indexOf('Result.');
  const toolsIdx    = md.indexOf('_Tools used:');
  const ticketIdx   = md.indexOf('_Filed support ticket:');
  const feedbackIdx = md.indexOf('_Feedback:');
  log('order: content < tools < ticket < feedback',
    contentIdx < toolsIdx && toolsIdx < ticketIdx && ticketIdx < feedbackIdx);
}

// ── Summary ──────────────────────────────────────────────────────────
console.log(`\n=== RESULTS ===`);
console.log(`✓ pass: ${pass}`);
console.log(`✗ fail: ${fail}`);
console.log(`total:  ${pass + fail}`);

process.exit(fail > 0 ? 1 : 0);
