/**
 * cryptoVault.ts
 *
 * Pluggable credential vault. Encrypts sensitive values (Dejavoo SPIn auth
 * keys, HPP keys, HPP webhook secrets, Transact API keys) before storing
 * them in the database. Used by every PaymentMerchant credential field.
 *
 * ─── Storage format ──────────────────────────────────────────────────────
 *   `v<N>:<provider-specific-blob>`
 *
 *   v1 = env-key AES-256-GCM      (current default)
 *   v2 = AWS KMS / Vault / HSM   (future — stub below)
 *
 * Legacy: ciphertexts WITHOUT a `vN:` prefix are decrypted as v1 for
 * backwards compatibility with anything written before this refactor.
 *
 * ─── Public API (stable across all providers) ────────────────────────────
 *   encrypt(plaintext)  → ciphertext (or null for empty input)
 *   decrypt(ciphertext) → plaintext  (or null on failure — logs, never throws)
 *   mask(plaintext)     → "••••••••last4"
 *
 * ─── Switching to KMS / Vault later ──────────────────────────────────────
 *   1. Implement v2 in kmsProvider.js (encrypt/decrypt against your KMS)
 *   2. Set VAULT_PROVIDER=kms in backend/.env
 *   3. Run a one-time migration script that re-encrypts every column that
 *      stores ciphertext (PaymentMerchant.spinAuthKey, hppAuthKey,
 *      hppWebhookSecret, transactApiKey). The script just calls
 *      `encrypt(decrypt(row.field))` per row — old v1 blobs decrypt via
 *      legacy path, new v2 blobs are written with v2 prefix. Mixed-version
 *      tables keep working throughout the migration.
 *   No call-site changes needed — encrypt/decrypt API is identical.
 *
 * ─── Why KMS at scale ────────────────────────────────────────────────────
 *   With env-key AES-256-GCM, ALL credentials share one master key. If
 *   the server's env leaks, every credential is exposed. KMS adds:
 *     • Per-credential data keys (envelope encryption) — one leaked DEK
 *       compromises one credential, not the whole table
 *     • Hardware-backed master keys (HSM) — never leave the KMS service
 *     • Audit logging — every decrypt is recorded centrally
 *     • Automatic key rotation with old-key fallback during transition
 *   Threshold to switch: ~hundreds of stores, PCI Level 1 compliance ask,
 *   or when insurance/legal asks for FIPS-140-2 backed key custody.
 */

import crypto from 'crypto';

const ALGO = 'aes-256-gcm';
const ACTIVE_PROVIDER = (process.env.VAULT_PROVIDER || 'env').toLowerCase();

// ═════════════════════════════════════════════════════════════════════════
// v1 — env-key AES-256-GCM (current default)
// ═════════════════════════════════════════════════════════════════════════

function loadEnvKey(): Buffer {
  const raw = process.env.DEJAVOO_VAULT_KEY || '';
  if (!raw) {
    console.warn(
      '[cryptoVault] No DEJAVOO_VAULT_KEY set — using ephemeral dev key. ' +
      'Set one in .env for production: ' +
      'node -e "console.log(require(\'crypto\').randomBytes(32).toString(\'hex\'))"'
    );
    return crypto.createHash('sha256').update('storv-dev-vault-key-change-me').digest();
  }
  // Accept either a 64-char hex string (raw 32-byte key) or any string
  // (hashed to 32 bytes). Hex is preferred — full entropy.
  if (/^[0-9a-fA-F]{64}$/.test(raw)) return Buffer.from(raw, 'hex');
  return crypto.createHash('sha256').update(raw).digest();
}

const ENV_KEY = loadEnvKey();

function encryptV1(plaintext: string): string {
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv(ALGO, ENV_KEY, iv);
  const encrypted = Buffer.concat([cipher.update(String(plaintext), 'utf8'), cipher.final()]);
  const tag = cipher.getAuthTag();
  return `${iv.toString('hex')}:${tag.toString('hex')}:${encrypted.toString('hex')}`;
}

function decryptV1(blob: string): string | null {
  const [ivHex, tagHex, dataHex] = blob.split(':');
  if (!ivHex || !tagHex || !dataHex) return null;
  const decipher = crypto.createDecipheriv(ALGO, ENV_KEY, Buffer.from(ivHex, 'hex'));
  decipher.setAuthTag(Buffer.from(tagHex, 'hex'));
  return Buffer.concat([decipher.update(Buffer.from(dataHex, 'hex')), decipher.final()]).toString('utf8');
}

// ═════════════════════════════════════════════════════════════════════════
// v2 — KMS / Vault / HSM (stub — implement when scaling)
// ═════════════════════════════════════════════════════════════════════════
// Reference implementations:
//   AWS KMS:  https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/kms/
//   GCP KMS:  https://cloud.google.com/kms/docs/reference/libraries
//   Vault:    https://github.com/hashicorp/vault-client-node
//
// Recommended pattern: envelope encryption.
//   1. Master key (KEK) lives in KMS, never leaves
//   2. Per-credential data key (DEK) is generated by KMS for each encrypt
//   3. Plaintext is AES-256-GCM encrypted with the DEK
//   4. The DEK itself is encrypted by the KEK (via KMS) and stored alongside
//      the ciphertext: `v2:<encrypted-dek>:<iv>:<tag>:<ciphertext>`
//   5. Decrypt: ask KMS to decrypt the DEK, then AES-decrypt the payload
//      with the recovered DEK
// Result: each credential has a unique DEK; KMS sees only DEK decrypt
// requests (rate-limitable, audit-loggable); a stolen DB still requires
// KMS access per-row to decrypt.

function encryptV2(_plaintext: string): never {
  throw new Error(
    'cryptoVault: v2 (KMS) provider is not implemented yet. ' +
    'See header comment for the upgrade path. ' +
    'Set VAULT_PROVIDER=env (or unset) to use the current provider.'
  );
}

function decryptV2(_blob: string): never {
  throw new Error('cryptoVault: v2 (KMS) provider is not implemented yet.');
}

// ═════════════════════════════════════════════════════════════════════════
// Public API
// ═════════════════════════════════════════════════════════════════════════

/**
 * Encrypt a plaintext credential. Returns versioned ciphertext.
 * Returns null for null/empty input — safe to pass optional fields directly.
 */
export function encrypt(plaintext: string | null | undefined): string | null {
  if (plaintext == null || plaintext === '') return null;

  if (ACTIVE_PROVIDER === 'kms') {
    return `v2:${encryptV2(plaintext)}`;
  }
  // Default: env-key AES-256-GCM
  return `v1:${encryptV1(plaintext)}`;
}

/**
 * Decrypt a versioned ciphertext. Returns plaintext, or null on failure.
 * Logs (not throws) so callers don't have to wrap every decrypt in try/catch.
 *
 * Backwards-compatible: ciphertexts WITHOUT a `vN:` prefix are treated as
 * v1 (env-key AES-256-GCM). Anything written before this refactor still
 * decrypts cleanly.
 */
export function decrypt(ciphertext: string | null | undefined): string | null {
  if (!ciphertext) return null;
  try {
    const versionMatch = /^(v\d+):(.*)$/s.exec(ciphertext);
    if (versionMatch) {
      const [, version, blob] = versionMatch;
      switch (version) {
        case 'v1': return decryptV1(blob);
        case 'v2': return decryptV2(blob);
        default:
          console.error(`[cryptoVault] Unknown ciphertext version: ${version}`);
          return null;
      }
    }
    // Legacy: no version prefix → assume v1
    return decryptV1(ciphertext);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error('[cryptoVault] decrypt failed:', message);
    return null;
  }
}

/**
 * Mask a plaintext for display. Shows last `visible` characters, dots the rest.
 *   mask('e78wAaxNyT')        → "••••••axNyT"  (default visible=4)
 *   mask('1234567890', 6)     → "••••567890"
 */
export function mask(plaintext: string | null | undefined, visible: number = 4): string {
  if (!plaintext) return '';
  const s = String(plaintext);
  if (s.length <= visible) return '•'.repeat(s.length);
  return '•'.repeat(Math.min(8, s.length - visible)) + s.slice(-visible);
}

/**
 * Generate a cryptographically random opaque token, used for things like
 * per-store webhook secrets. Returns a hex string of N bytes (default 32 = 64 chars).
 *
 * Webhook secret usage:
 *   const secret = randomToken();         // generate once
 *   const enc = encrypt(secret);          // store encrypted in DB
 *   url = `${BACKEND_URL}/.../webhook/${secret}`;  // give to merchant for iPOSpays
 */
export function randomToken(bytes: number = 32): string {
  return crypto.randomBytes(bytes).toString('hex');
}
