directories:
  output: dist-electron
  buildResources: build
appId: com.storeveu.pos
productName: StoreVeu POS
copyright: Copyright © 2025 StoreVeu
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - public/icon.*
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: public/icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  installerIcon: public/icon.ico
  shortcutName: StoreVeu POS
mac:
  target: dmg
  icon: public/icon.icns
linux:
  target: AppImage
  icon: public/icon.png
electronVersion: 33.4.11
